Create de.lua
Qbox-project/qbx_diving pull request #35
Opened 2024-10-05 16:20 UTC by RoYaL69

## Description

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-10-05 16:23 UTC, Manason requested changes
This looks like a QB style locale, not an ox_lib style one.

2024-10-05 16:36 UTC, RoYaL69 commented
just copied from en.lua, translated it and added the bottom from other languages with the 'de' switch. Other Projects use json from ox but here it is oldschool lua. Also if you look into is.lua there are much more values then in en.lua. Can u tell me whats exactly wrong do you think?

2024-10-05 16:38 UTC, RoYaL69 commented
> This looks like a QB style locale, not an ox_lib style one.

just copied from en.lua, translated it and added the bottom from other languages with the 'de' switch. Other Projects use json from ox but here it is oldschool lua. Also if you look into is.lua there are much more values then in en.lua. Can u tell me whats exactly wrong do you think?

2024-10-06 18:21 UTC, mafewtm approved these changes

2024-10-06 18:22 UTC, merged