switch qb locale to ox_lib locale
Qbox-project/qbx_diving pull request #36
Opened 2024-10-31 19:09 UTC by EdyzPW

2024-11-01 15:05 UTC, Manason approved these changes

2024-11-01 17:16 UTC, solareon requested changes
Any reason why not all the original locales were converted?

2024-11-01 22:52 UTC, EdyzPW commented
At the time I thought some of those were incomplete or missing something, now that I look better at it I see that there are almost if not all the translations needed there. If it is necessary I will make a new commit/PR adding those ones

2024-11-02 13:09 UTC, EdyzPW commented
I have added all of the original translations. I thin you can now merge the PR if you like it.

2024-11-05 16:32 UTC, mafewtm approved these changes

2024-11-05 16:35 UTC, merged